name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    
    - name: Setup global
      run: npm install -g gatsby gh-pages

    - name: Setup local
      run: npm install
    
    - name: Setup github
      run: |
        git config --global user.name ""
        git config --global user.email ""

    - name: Build
      run: npm run build

    - name: Deploy
      run: npm run deploy -- --repo 'https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}'
